# Generated by Django 5.2.4 on 2025-09-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='edad',
        ),
        migrations.AddField(
            model_name='registro',
            name='password',
            field=models.CharField(default='temp1234', max_length=128),
            preserve_default=False,
        ),
    ]
