# Generated by Django 5.1.4 on 2025-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoAPP', '0002_remove_registro_edad_registro_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
